version: '2'

services:

  wordpress:
    build: .
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_PASSWORD: senhasupersegura
      WORDPRESS_DB_USER: usuariosuperseguro
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 3000:80
    volumes:
    - ./data/institucional_uploads:/var/www/html/wp-content/uploads
    - ./data/institucional_plugins:/var/www/html/wp-content/plugins
    - ./themes/votasp:/var/www/html/wp-content/themes/votasp
    links:
    - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: senhasupersegura
      MYSQL_USER: usuariosuperseguro
      MYSQL_ROOT_PASSWORD: senhasupersegura
    volumes:
    - ./data/institucional-db:/var/lib/mysql
